apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
spec:
  selector:
    app: nginx-proxy-manager
  ports:
    - name: nginxport
      protocol: TCP
      port: 80
      targetPort: 80
    - name: webui
      protocol: TCP
      port: 81
      targetPort: 81
    - name: justtcp
      protocol: TCP
      port: 443
      targetPort: 443
