apiVersion: apps/v1
kind: Deployment
metadata:
# Name your deployment
  name: nginx-proxy-manager  
spec:
# Number of replicas (instances) of the pod
  replicas: 1  
  selector:
    matchLabels:
    # Selector to match labels for pod assignment
      app: nginx-proxy-manager  
  template:
    metadata:
      labels:
      # Labels the pods created by this deployment
        app: nginx-proxy-manager  
    spec:
      containers:
      # Name the Kubernetes container
      - name: nginx-proxy-manager  
      # Docker image for Nginx Proxy Manager
        image: jc21/nginx-proxy-manager:latest  
        ports:
        - containerPort: 80  # Port 80 exposed
        - containerPort: 81  # Port 81 exposed 
        - containerPort: 443  # Port 443 exposed 
        env:
        - name: DB_MYSQL_HOST
          value: "mariadb"  # MariaDB host
        - name: DB_MYSQL_PORT
          value: "3306"  # MariaDB port
        - name: DB_MYSQL_USER
          value: "proxy_manager_user"  # MariaDB username
        - name: DB_MYSQL_PASSWORD
          value: "user_pass"  # MariaDB password
        - name: DB_MYSQL_NAME
          value: "proxy-manager"  # MariaDB database name
          # Mount path for persistent data
        volumeMounts:
        - name: data
          mountPath: /data  
        - name: letsencrypt
        # Mount path for Let's Encrypt certificates
          mountPath: /etc/letsencrypt  
      volumes:
      - name: data
        persistentVolumeClaim:
        # PersistentVolumeClaim for Nginx data
          claimName: nginx-data-pvc  
      - name: letsencrypt
        persistentVolumeClaim:
        # PersistentVolumeClaim for Let's Encrypt certificates
          claimName: letsencrypt-pvc  
