apiVersion: v1
kind: PersistentVolumeClaim
metadata:
# Name of the PersistentVolumeClaim for Nginx data
  name: nginx-data-pvc  
spec:
  accessModes:
  # Define access mode as ReadWriteOnce
    - ReadWriteOnce  
  resources:
    requests:
    # Request 1GiB of storage
      storage: 1Gi  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-pvc  # PersistentVolumeClaim for Let's Encrypt
spec:
  accessModes:
    - ReadWriteOnce  # Use mode as ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Request 1GiB of storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
# Name of the PersistentVolumeClaim for MariaDB data
  name: mariadb-data-pvc  
spec:
 # Add access mode as ReadWriteOnce
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
    # Request 1GiB of storage
      storage: 1Gi  
